{% set data= load_setup_py_data() %}
package:
  name: ts-ess-labjack
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.3
    - ts-idl {{ idl_version }}
    - ts-utils
    - ts-salobj {{ salobj_version }}
    - labjack-ljm
  source_files:
    - python
    - tests
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - ts-idl
    - ts-salobj
    - ts-utils
    - ts-ess-common
